import asyncio
from collections.abc import Iterable, Mapping
from contextlib import suppress
from pathlib import Path
from typing import ClassVar

from liquid import render
from openai.types.responses.function_tool_param import FunctionToolParam

from agent_server.agent.agent_manager import AgentManager
from agent_server.core.tools._utils import ConstraintPolicy
from agent_server.schemas.activity import (
    ClientEvent,
    SessionConfigChangeEvent,
    StatusEvent,
    StreamingEvent,
    UserMessageEvent,
)
from agent_server.storage.session_store import SessionStore

TOOL_NAME = "agent"

AGENT_TOOL_DESCRIPTION = """Launch a new agent to handle complex, multistep tasks autonomously.

When using this Agent tool, you must specify a subagent_type parameter to select which agent type to use."""

AGENT_TOOL_DEFINITION: FunctionToolParam = {
    "type": "function",
    "name": "agent",
    "description": AGENT_TOOL_DESCRIPTION,
    "parameters": {
        "type": "object",
        "properties": {
            "description": {
                "type": "string",
                "description": "A short (3-5 words) description of the task",
            },
            "prompt": {
                "type": "string",
                "description": "The task for the agent to perform",
            },
            "subagent_type": {
                "type": "string",
                "description": "The type of specialized agent to use for this task.",
            },
        },
        "required": [
            "description",
            "prompt",
            "subagent_type",
        ],
        "additionalProperties": False,
    },
    "strict": True,
}

DEFAULT_TIMEOUT_MINUTES = 15

TIMED_OUT_MESSAGE = "The agent has timed out after {{minutes}} of inactivity. Please try again."
ERROR_MESSAGE = "The agent has unknown error. Please continue without a sub-agent."


class AgentTool:
    TOOLS: ClassVar[dict[str, FunctionToolParam]] = {
        TOOL_NAME: AGENT_TOOL_DEFINITION,
    }

    def __init__(
        self,
        streaming_events: asyncio.Queue[StreamingEvent],
        working_dir: Path,
        session_database: Path,
    ) -> None:
        self.streaming_events = streaming_events
        self.working_dir = working_dir
        self.session_database = session_database
        self._agent_managers: dict[str, AgentManager] = {}

    async def submit_event(self, agent_id: str, event: ClientEvent) -> bool:
        agent_manager = self._agent_managers.get(agent_id)
        if agent_manager is None:
            return False

        await agent_manager.submit_event(event)
        return True

    async def broadcast_event(self, event: SessionConfigChangeEvent) -> None:
        for agent_manager in tuple(self._agent_managers.values()):
            await agent_manager.submit_event(event)

    async def execute(self, **arguments: object) -> str:
        """Spawns a sub-agent using the AgentManager and sends it the prompt generated by the tool call.
        We forward every event, wait for the sub-agent to emit agent_turn_ended, and then close the AgentManager.
        If the sub-agent takes longer than DEFAULT_TIMEOUT_MINUTES we close it and send TIMED_OUT_MESSAGE.
        """
        # TODO: For now description and subagent_type are not used.
        prompt_arg = arguments.get("prompt")
        # The sub_agent_id is injected when the response is generated.
        sub_agent_id = str(arguments.get("sub_agent_id"))

        sub_agent_events: asyncio.Queue[StreamingEvent] = asyncio.Queue()
        agent_manager = AgentManager(
            streaming_events=sub_agent_events,
            working_dir=self.working_dir,
            session_database=self.session_database,
            agent_id=sub_agent_id,
            process_tree_root=False,
        )
        if sub_agent_id in self._agent_managers:
            raise ValueError(f"Sub-agent is already running: {sub_agent_id}")
        self._agent_managers[sub_agent_id] = agent_manager

        agent_manager_task = asyncio.create_task(agent_manager.start_manager())
        try:
            await agent_manager.submit_event(UserMessageEvent(type="user_message", content=str(prompt_arg)))

            while True:
                try:
                    event = await self._wait_for_event_or_manager_exit(
                        sub_agent_events,
                        agent_manager_task,
                    )
                except TimeoutError:
                    return render(TIMED_OUT_MESSAGE, minutes=DEFAULT_TIMEOUT_MINUTES)

                await self.streaming_events.put(event)
                match event:
                    case StatusEvent(status_id="agent_turn_ended"):
                        return self._load_last_assistant_message(agent_id=sub_agent_id)
        finally:
            try:
                await agent_manager.shutdown()
                await agent_manager_task
            finally:
                await self._forward_queued_events(sub_agent_events)
                if self._agent_managers.get(sub_agent_id) is agent_manager:
                    del self._agent_managers[sub_agent_id]

    @staticmethod
    async def _wait_for_event_or_manager_exit(
        sub_agent_events: asyncio.Queue[StreamingEvent],
        agent_manager_task: asyncio.Task[None],
    ) -> StreamingEvent:
        event_task = asyncio.create_task(sub_agent_events.get())
        try:
            done, _ = await asyncio.wait(
                {event_task, agent_manager_task},
                timeout=DEFAULT_TIMEOUT_MINUTES * 60,
                return_when=asyncio.FIRST_COMPLETED,
            )
            if not done:
                raise TimeoutError
            if agent_manager_task in done:
                await agent_manager_task
                raise RuntimeError("Sub-agent manager stopped unexpectedly.")
            return event_task.result()
        finally:
            if not event_task.done():
                event_task.cancel()
            with suppress(asyncio.CancelledError):
                await event_task

    async def _forward_queued_events(self, events: asyncio.Queue[StreamingEvent]) -> None:
        while True:
            try:
                event = events.get_nowait()
            except asyncio.QueueEmpty:
                return
            await self.streaming_events.put(event)

    def check_constraint(self, **arguments: object) -> ConstraintPolicy:
        """For now always ask to spawn a subagent."""
        return ConstraintPolicy.ALLOW

    def _load_last_assistant_message(self, agent_id: str) -> str:
        """Loads the latest assistant text from a session database if it exists."""

        with SessionStore(self.session_database) as session_store:
            session_messages = session_store.load_session_chat_messages(agent_id=agent_id)

        for session_message in reversed(session_messages):
            message = session_message.chat_message.message
            if message.get("role") != "assistant":
                continue

            content = message.get("content")
            if isinstance(content, str):
                return content
            if not isinstance(content, Iterable):
                return ERROR_MESSAGE

            text_parts: list[str] = []
            for item in content:
                if not isinstance(item, Mapping):
                    continue

                match item.get("type"):
                    case "output_text":
                        text = item.get("text")
                    case "refusal":
                        text = item.get("refusal")
                    case _:
                        text = None
                if isinstance(text, str):
                    text_parts.append(text)

            return "\n".join(text_parts)

        return ERROR_MESSAGE
