import asyncio
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import ClassVar
from uuid import uuid4

from openai.types.responses.function_tool_param import FunctionToolParam

from agent_server.agent.agent_manager import AgentManager
from agent_server.core.tools._utils import ConstraintPolicy
from agent_server.schemas.activity import StatusEvent, StreamingEvent, UserMessageEvent
from agent_server.storage.session_store import SessionStore

TOOL_NAME = "agent"

AGENT_TOOL_DESCRIPTION = """Launch a new agent to handle complex, multistep tasks autonomously.

When using this Agent tool, you must specify a subagent_type parameter to select which agent type to use."""

AGENT_TOOL_DEFINITION: FunctionToolParam = {
    "type": "function",
    "name": "agent",
    "description": AGENT_TOOL_DESCRIPTION,
    "parameters": {
        "type": "object",
        "properties": {
            "description": {
                "type": "string",
                "description": "A short (3-5 words) description of the task",
            },
            "prompt": {
                "type": "string",
                "description": "The task for the agent to perform",
            },
            "subagent_type": {
                "type": "string",
                "description": "The type of specialized agent to use for this task.",
            },
        },
        "required": [
            "description",
            "prompt",
            "subagent_type",
        ],
        "additionalProperties": False,
    },
    "strict": True,
}

DEFAULT_TIMEOUT_MINUTES = 15

TIMED_OUT_MESSAGE = "The agent has timed out after {{minutes}} of inactivity. Please try again."
ERROR_MESSAGE = "The agent has unknown error. Please continue without a sub-agent."


class AgentTool:
    TOOLS: ClassVar[dict[str, FunctionToolParam]] = {
        TOOL_NAME: AGENT_TOOL_DEFINITION,
    }

    def __init__(
        self,
        streaming_events: asyncio.Queue[StreamingEvent],
        working_dir: Path,
        session_database: Path,
    ) -> None:
        self.streaming_events = streaming_events
        self.working_dir = working_dir
        self.session_database = session_database

    async def execute(self, **arguments: object) -> str:
        """Spawns a sub-agent using the AgentManager and sends it the prompt generated by the tool call.
        We wait for the sub-agent to finish its turn and send a agent_turn_ended event and then close the AgentManager.
        If the sub-agent takes longer than DEFAULT_TIMEOUT_MINUTES we close it and send TIMED_OUT_MESSAGE.
        """
        # TODO: For now description and subagent_type are not used.
        prompt_arg = arguments.get("prompt")

        # TODO: Later this id should also have the subagent-type
        sub_agent_id = f"sub-{str(uuid4())[:8]}"

        sub_agent_events: asyncio.Queue[StreamingEvent] = asyncio.Queue()
        agent_manager = AgentManager(
            streaming_events=sub_agent_events,
            working_dir=self.working_dir,
            session_database=self.session_database,
            agent_id=sub_agent_id,
        )

        agent_manager_task = asyncio.create_task(agent_manager.start_manager())
        await agent_manager.submit_event(UserMessageEvent(type="user_message", content=str(prompt_arg)))

        while True:
            event = await sub_agent_events.get()
            match event:
                case StatusEvent(status_id="agent_turn_ended"):
                    await agent_manager.shutdown()
                    if not agent_manager_task.done():
                        await agent_manager_task
                    last_assistant_message = self._load_last_assistant_message(agent_id=sub_agent_id)
                    return last_assistant_message
                case _:
                    await self.streaming_events.put(event)

    def check_constraint(self, **arguments: object) -> ConstraintPolicy:
        """For now always ask to spawn a subagent."""
        return ConstraintPolicy.ALLOW

    def _load_last_assistant_message(self, agent_id: str) -> str:
        """Loads the latest assistant text from a session database if it exists."""

        with SessionStore(self.session_database) as session_store:
            session_messages = session_store.load_session_chat_messages(agent_id=agent_id)

        for session_message in reversed(session_messages):
            message = session_message.chat_message.message
            if message.get("role") != "assistant":
                continue

            content = message.get("content")
            if isinstance(content, str):
                return content
            if not isinstance(content, Iterable):
                return ERROR_MESSAGE

            text_parts: list[str] = []
            for item in content:
                if not isinstance(item, Mapping):
                    continue

                match item.get("type"):
                    case "output_text":
                        text = item.get("text")
                    case "refusal":
                        text = item.get("refusal")
                    case _:
                        text = None
                if isinstance(text, str):
                    text_parts.append(text)

            return "\n".join(text_parts)

        return ERROR_MESSAGE
